- name: mongodb Data dirctory are created
  file: path=/data/mongodb/ state=directory mode=0755
  ignore_errors: yes
  tags: [mongodb]

- name: MongoDB is running
  docker_container:
#   restart_policy: always
    name: mongodb
    image: bitnami/mongodb:latest 
    ports: 
    - "27017:27017"
    privileged: yes
#    env:
#      MONGODB_USERNAME: ude
#      MONGODB_PASSWORD: ude
#      MONGODB_DATABASE: ude
    volumes:
      - /data/mongodb:/bitnami/mongodb
  when: not skip_ui is defined
  tags: [mongodb]
